block_broker:
  ip: "0.0.0.0"
  port: 12347

log_broker:
  ip: "0.0.0.0"
  port: 56791

bitvmx_broker:
  ip: "0.0.0.0"
  # port: 9094
  port: 44444

broker_client_id: 335

user_broker:
  ip: "0.0.0.0"
  port: 5554 # hardcoded in user-api crate
