bitcoin:
  network: regtest
  wallet: test_wallet
  url: <to_patch_in_host>

key_manager:
  network: regtest
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: <to_patch_in_host>
  path: /tmp/regtest/op_1/keys.db

storage:
  path: /tmp/regtest/op_1/storage.db

comms:
  address: 172.20.0.11:61180
  priv_key: config/keys/op_1.key
  storage_path: /tmp/regtest/op_1/comms.db

broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 22222
  ip: 0.0.0.0
  priv_key: config/keys/services.key
  storage: 
    path: /tmp/regtest/op_1/broker.db

components:
  l2:
    pubkey_hash: <to_patch_in_host>
    id: 0
  bitvmx:
    pubkey_hash: <to_patch_in_host>
    id: 0
  emulator:
    pubkey_hash: <to_patch_in_host>
    id: 0
  prover:
    pubkey_hash: <to_patch_in_host>
    id: 0

testing:
  l2:
    priv_key: config/keys/l2.key
    id: 0
  emulator:
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    priv_key: config/keys/prover.key
    id: 0

coordinator:
  throtthle_bitcoin_updates_until_sync: 0
  throtthle_bitcoin_updates: 0

client: 
  retry: 1
  retry_delay: 1000

wallet:
  db_path: /tmp/regtest/op_1/wallet.db
  start_height: 0
