bitcoin:
  network: regtest
  wallet: test_wallet
  url: <to_patch_in_host>
  username: ''
  password: ''
key_manager:
  network: regtest
  key_derivation_path: m/101/1/0/0/
  mnemonic_sentence: <to_patch_in_host>
  mnemonic_passphrase: <to_patch_in_host>

key_storage:
  password: <to_patch_in_host>
  path: /tmp/regtest/op_9/keys.db

storage:
  path: /tmp/regtest/op_9/storage.db

comms:
  address: 172.20.0.19:61188
  priv_key: config/keys/op_9.key
  storage_path: /tmp/regtest/op_9/comms.db

broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 55559
  ip: 0.0.0.0
  priv_key: config/keys/services.key
  storage: 
    path: /tmp/regtest/op_9/broker.db

components:
  l2:
    pubkey_hash: <to_patch_in_host>
    id: 0
  bitvmx:
    pubkey_hash: <to_patch_in_host>
    id: 0
  emulator:
    pubkey_hash: <to_patch_in_host>
    id: 0
  prover:
    pubkey_hash: <to_patch_in_host>
    id: 0
  garbler:
    pubkey_hash: <to_patch_in_host>
    id: 0

testing:
  l2:
    priv_key: config/keys/l2.key
    id: 0
  emulator:
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    priv_key: config/keys/prover.key
    id: 0
  garbler:
    priv_key: config/keys/garbler.key
    id: 0

coordinator_throttle:
  init_interval: 10
  busy_interval: 50
  idle_interval: 200

bitvmx_throttle:
  busy_interval: 20
  idle_interval: 200

client: 
  retry: 1
  retry_delay: 1000

wallet:
  db_path: /tmp/regtest/op_9/wallet.db
  start_height: 0
