[workspace]

[package]
name = "run-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.30", features = ["derive"] }
nix = { version = "0.29", features = ["signal", "process"] }

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "macros", "signal", "sync", "time"]
