version: 2

registries:
  github:
    type: git
    url: https://github.com/FairgateLabs
    username: x-access-token
    password: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}

updates:
  - package-ecosystem: "cargo"
    directory: "/" # main workspace
    schedule:
      interval: "hourly"
    registries:
      - github

  - package-ecosystem: "cargo"
    directory: "/check-fork/zkp/guest" # guest workspace
    schedule:
      interval: "hourly"