[workspace]
resolver = "2"
members = ["qa-tools", "common", "block-indexer", "log-indexer", "transaction-dispatcher", "key-manager", "check-fork", "coordinator", "actors-mocking", "check-fork/zkp"]

[workspace.dependencies]
# alloy-rs-core
alloy-dyn-abi = "0.8.22"
alloy-json-abi = "0.8.22"
alloy-primitives = "0.8.22"
alloy-sol-types = "0.8.22"
# alloy
alloy-contract = "0.13.0"
alloy-json-rpc = "0.13.0"
alloy-provider = "0.13.0"
alloy-pubsub = "0.13.0"
alloy-rpc-client = "0.13.0"
alloy-rpc-types = "0.13.0"
alloy-signer = "0.13.0"
alloy-signer-local = { version = "0.13.0" }
alloy-transport = "0.13.0"
#
anyhow = "1.0.94"
clap = "4.5.30"
hex = "0.4.3"
log = "0.4.22"
log4rs = "1.3.0"
mockall = "0.13.1"
primitive-types = { version = "0.13.1", features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.11"
tokio = { version = "1.41.1" }
config = "0.15.8"
storage-backend = { package = "rust-bitvmx-storage-backend", git = "ssh://git@github.com/FairgateLabs/rust-bitvmx-storage-backend.git", rev = "7f40d056f86295e3fd2a4f268f923ca3b4e70fbf" }
union-contracts = { package = "union-bridge-contracts", git = "ssh://git@github.com/FairgateLabs/bitvmx-union-bridge-contracts.git", tag = "v0.0.1-alpha.1" }

#dev-dependencies
tempfile = "3.16.0"
env_logger = "0.11.6"
