[workspace]
resolver = "2"
members = [
    "crates/block-indexer",
    "crates/check-fork",
    "crates/check-fork/tester",
    "crates/check-fork/zkp",
    "crates/common",
    "crates/coordinator",
    "crates/key-manager",
    "crates/log-indexer",
    "crates/op-funding",
    "crates/protocol-params",
    "crates/transaction-dispatcher",
    "crates/user-api",
]

[workspace.package]
version = "0.4.0"
license = "MIT"
rust-version = "1.95"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
multiple-crate-versions = "allow"
cargo-common-metadata = "allow"

[workspace.lints.rust]
unreachable_pub = "warn"

[workspace.dependencies]
# alloy
alloy-contract = "1.0.42"
# alloy-rs-core
alloy-dyn-abi = "1.4.1"
alloy-json-abi = "1.4.1"
alloy-json-rpc = "1.0.42"
alloy-primitives = "1.4.1"
alloy-provider = "1.0.42"
alloy-pubsub = "1.0.42"
alloy-rpc-client = "1.0.42"
alloy-rpc-types = "1.0.42"
alloy-signer = "1.0.42"
alloy-signer-local = { version = "1.0.42" }
alloy-sol-types = "1.4.1"
alloy-transport = "1.0.42"
#
anyhow = "1.0.102"
axum = "0.8.9"
bincode = { version = "2.0.1", features = ["serde"] }
# Version pinned to 0.32.6 for compatibility with bitvmx-emulator crate
bitcoin = { version = "=0.32.6", features = ["std", "rand-std", "serde"] }
chrono = { version = "0.4.42", default-features = false, features = ["clock", "std"] }
clap = "4.5.61"
config = "0.15.22"
hex = "0.4.3"
message-broker = { package = "bitvmx-broker", git = "https://github.com/FairgateLabs/rust-bitvmx-broker.git", tag = "v0.6.1" }
mockall = "0.13.1"
musig2 = { version = "0.2.4", features = ["serde", "rand"] }
primitive-types = { version = "0.13.1", features = ["std", "serde"] }
protocol-params = { path = "crates/protocol-params" }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.33"
sha2 = "0.11.0"
storage-backend = { package = "rust-bitvmx-storage-backend", git = "https://github.com/FairgateLabs/rust-bitvmx-storage-backend.git", rev = "16a01bfe316266bdac080828e260cd191fcb3cde" }

#dev-dependencies
tempfile = "3.16.0"
thiserror = "2.0.18"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tokio = { version = "1.52.3" }
tower-http = { version = "0.6.11", features = ["timeout", "trace"] }
tracing = "=0.1.43"
tracing-appender = "=0.2.4"
tracing-log = "=0.2.0"
tracing-subscriber = { version = "=0.3.22", features = ["env-filter", "json"] }
union-contracts = { package = "union-bridge-contracts", git = "https://github.com/rsksmart/union-bridge-contracts.git", tag = "v0.4.1-alpha" }
uuid = { version = "1.23.1", features = ["v4", "serde"] }
