[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.prep-commit]
dependencies = [
    "format"
]

[tasks.prep-push]
dependencies = [
    "format",
    "test"
]