[hooks]
commit-msg = ".hooks/check_commit_message"
pre-commit = "cargo fmt --check"
pre-push = ".hooks/check_branch_name && RISC0_SKIP_BUILD=1 cargo clippy --workspace --all-targets --all-features -- -D warnings && RUN_MODE=ci cargo test --features test-utils"