[package]
name = "actors-mocking"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-contract = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-eips = "1.0.12"
anyhow = { workspace = true }
clap = { version = "4.5.30", features = ["derive"] }
common = { path = "../common" }
key-manager = { path = "../key-manager" }
tokio = { version = "1.45", features = ["rt-multi-thread", "signal", "io-std"] }

[features]
default = []
anvil = ["common/anvil"]
