[package]
name = "actors-mocking"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-contract = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-node-bindings = "1.0.12"
alloy-eips = "1.0.12"
anyhow = { workspace = true }
clap = { version = "4.5.30", features = ["derive"] }
common = { path = "../common" }
tokio = { version = "1.45", features = ["rt-multi-thread", "signal", "io-std"] }
union-contracts = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
# TODO(jira) https://rsklabs.atlassian.net/browse/ub-176
hex = "0.4"
bitcoin = { version = "0.32.4", features = ["std", "rand-std", "serde"] }
chrono = "0.4.41"
uuid = { version = "1.11.0", features = ["v4"] }

[features]
default = []
anvil = ["common/anvil"]
