[package]
name = "actors-mocking"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-contract = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-node-bindings = "0.13.0"
alloy-signer-local = { workspace = true }
alloy-eips = "0.13.0"
anyhow = { workspace = true }
clap = { version = "4.5.30", features = ["derive"] }
common = { path = "../common" }
tokio = { version = "1.45", features = ["rt-multi-thread", "signal", "io-std"] }
union-contracts = { workspace = true }
serde_json = { workspace = true }
# TODO(jira) https://rsklabs.atlassian.net/browse/ub-176
bitvmx-client = { workspace = true }
hex = "0.4"

[features]
default = []
anvil = ["common/anvil"]