[package]
name = "user-api"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
common = { path = "../common" }
log = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true }
transaction-dispatcher = { path = "../transaction-dispatcher", features = ["types"] }
uuid = { workspace = true }

[lints]
workspace = true
