use std::env;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::Path;

const CARGO_MANIFEST_DIR: &str = env!("CARGO_MANIFEST_DIR");

fn main() {
    let mode = env::var("RUN_MODE").unwrap_or_else(|_| "local".into());
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("abi.rs");

    fs::write(&out_path, "// auto-generated by build.rs\n").expect("Failed to clear abi.rs");

    let contracts = [
        ("SolPegManager", "PegManager"),
        ("SolBitcoinManager", "BitcoinManager"),
    ];

    let mut file = OpenOptions::new()
        .append(true)
        .open(&out_path)
        .expect("Failed to open abi.rs");

    writeln!(file, "use alloy_sol_types::sol;").unwrap();

    let project_root = Path::new(CARGO_MANIFEST_DIR)
        .parent()
        .and_then(|p| p.to_str())
        .expect("Failed to get default_destination");

    for (struct_name, file_name) in &contracts {
        let abi_path = format!("{project_root}/config/{}/abi/{}.json", mode, file_name);

        if !Path::new(&abi_path).exists() {
            panic!("ABI file not found: {}", abi_path);
        }

        writeln!(
            file,
            r#"
sol!(
    #[sol(rpc)]
    {struct_name},
    "{abi_path}"
);
"#,
        )
        .unwrap();

        // TODO(iago) check if removing re-builds always
        // println!("cargo:rerun-if-changed={}", abi_path);
    }

    // TODO(iago) check if removing re-builds always
    // println!("cargo:rerun-if-env-changed=RUN_MODE");
}
