[package]
name = "transaction-dispatcher"
version = "0.1.0"
edition = "2024"

[features]
# TODO(Jira) remove in scope of https://rsklabs.atlassian.net/browse/UB-214
default = ["types"]
types = []

[dependencies]

alloy-contract = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true, features = ["ws"] }
alloy-rpc-types = { workspace = true, features = ["debug"] }
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-transport = { workspace = true }
anyhow = { workspace = true }
bitcoin = { workspace = true }
common = { path = "../common" }
env_logger = { workspace = true }
hex = { workspace = true, features = ["serde"] }
key-manager = { path = "../key-manager" }
log = { workspace = true }
multiaddr = "0.18.2"
musig2 = { workspace = true }
primitive-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
union-contracts = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
