[package]
name = "qa-tools-check-fork"
version = "0.1.0"
edition = "2024"
resolver = "2"

[[bin]]
name = "check_fork_runner"
path = "src/check_fork_runner.rs"

[dependencies]
check-fork = { path = "../../check-fork" }
common = { path = "../../common" }

qa-tools-common = { path = "../common" }

bitcoin = "0.32.4"
clap = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = "0.4.3"
primitive-types = { version = "0.13.1", features = ["std", "serde"] }
methods = { path = "methods" }
zkvm_cli_serde = { package = "cli_serde", git = "ssh://git@github.com/FairgateLabs/rust-bitvmx-zk-proof.git", branch = "poc-generalise-host" }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["full"] }
