[package]
name = "rsk-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

alloy-provider = { workspace = true, features = ["ws"] }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }

alloy-dyn-abi = "0.8.21"
alloy-json-abi = "0.8.21"
alloy-pubsub = { version = "0.11.1" }
alloy-rpc-types = "0.11.1"
tokio = { workspace = true, features = ["rt-multi-thread"] }
