bitcoin:
  network: testnet
  url: http://<BITCOIN_USER>:<BITCOIN_PASSWORD>@<BITCOIND_HOST>:18332
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: <KEY_STORAGE_PASSWORD>
  path: /tmp/op_4/keys.db
storage:
  path: /tmp/op_4/storage.db
p2p:
  address: /ip4/<OPERATOR_IP>/tcp/61180
  key: config/keys/op_4.key
  peer_id_file: peer_id
  timeout: 5
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4807400
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker_storage:
  path: /tmp/op_4/broker.db
broker_port: 22222
client:
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000

wallet:
  db_path: /tmp/testnet/op_4/wallet.db
  start_height: 4807400
