bitcoin:
  network: testnet
  url: http://bitcoin:39048j03%40slk@bitcoind-01.testnet.ub.iovlabs.net:18332
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet

key_storage:
  password: secret_password_1
  path: /tmp/testnet/wallet/keys.db

storage:
  path: /tmp/testnet/wallet/storage.db

wallet:
  receive_key: cUVFBGCCjw5JGY2DUY5HTtKoHevMHs675aFkXVLvXeE4jV7GPeGb
  change_key: cVTMy1VXsEqT4z3nT3w8vupAmqBTjZBmyyE38TYP9kju9rQWpK9F
  db_path: /tmp/testnet/wallet/wallet.db
  start_height: 4631993
