bitcoin:
  network: regtest
  url: http://<BITCOIN_USER>:<BITCOIN_PASSWORD>@<BITCOIND_HOST>:18443
  username: ''
  password: ''
  wallet: test_wallet

key_manager:
  network: regtest

key_storage:
  password: <KEY_STORAGE_PASSWORD>
  path: /tmp/regtest/wallet/keys.db

storage:
  path: /tmp/regtest/wallet/storage.db

wallet:
  receive_key: <RECEIVE_WIF_KEY>
  change_key: <CHANGE_WIF_KEY>
  db_path: /tmp/regtest/wallet/wallet.db
  start_height: 0
