# configuration for regtest

network = "regtest"
sats_per_byte = 5

# Default local regtest node settings for bitcoind node run inside docker container using bitcoind.rs
# Wallet path required for wallet RPCs (getnewaddress, etc.); mainwallet is created by start_blockchains.sh
rpc_url = "http://127.0.0.1:18443"
rpc_user = "foo"
rpc_password = "rpcpassword"

# Root path for wallet databases (UTXOs and pending transactions)
db_path = ".union_bridge/bitcoin-wallet"