# configuration for testnet

network = "testnet"
sats_per_byte = 5

# Default local regtest node settings for bitcoind node run inside docker container using bitcoind.rs 
rpc_url = "http://<BITCOIND_HOST>:18332"
rpc_user = "<RPC_USER>"
rpc_password = "<RPC_PASSWORD>"

# Root path for wallet databases (UTXOs and pending transactions)
db_path = ".union_bridge/bitcoin-wallet"

