[package]
name = "run"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
key-manager = { workspace = true }
nix = { workspace = true }
sysinfo = "0.32.1"
tokio = { workspace = true }

[lints]
workspace = true
