key_store:
  path: "/Users/illuque/.union_bridge/keystore/ab98c3c8-a772-4c44-b3a7-99864663b8cb"
transaction:
  gas_bumps_t1: 3
server:
  url: "0.0.0.0:3000"

provider:
  rootstock:
    url: "ws://127.0.0.1:8545"