[package]
name = "block-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
log4rs = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }
common = { path = "../common" }
rsk-provider = { path = "../rsk-provider" }

[dev-dependencies]
tempfile = "3.16.0"