[package]
name = "block-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
env_logger = { workspace = true }

[features]
test-mocks = ["common/test-mocks"]
test-utils = ["common/test-utils"]