[package]
name = "block-indexer"
version = "0.1.0"
edition = "2024"

[lints.clippy]
all = "deny"
pedantic = "deny"

[dependencies]
common = { path = "../common" }

anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
primitive-types = { workspace = true }
tempfile = { workspace = true }

[features]
default = ["fresh_node"] # temporary, for dev convenience
anvil = ["common/anvil"]
fresh_node = []
