block_broker:
  ip: "0.0.0.0"
  port: 12348

log_broker:
  ip: "0.0.0.0"
  port: 56792

bitvmx_broker:
  ip: "0.0.0.0"
  # port: 9094
  port: 55554

broker_client_id: 336

user_broker:
  ip: "0.0.0.0"
  port: 5556 # hardcoded in user-api crate
