bitcoin:
  network: regtest
  wallet: test_wallet
  url: <to_patch_in_host>

key_manager:
  network: regtest
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: <to_patch_in_host>
  path: /tmp/regtest/op_6/keys.db

storage:
  path: /tmp/regtest/op_6/storage.db

p2p:
  address: /ip4/172.20.0.16/tcp/61185
  key: config/keys/op_6.key
  peer_id_file: peer_id
  timeout: 5

coordinator:
  throtthle_bitcoin_updates_until_sync: 0
  throtthle_bitcoin_updates: 0
#  estimate_fee: 8

broker_storage: 
  path: /tmp/regtest/op_6/broker.db

broker_port: 55556

client: 
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000

wallet:
  db_path: /tmp/regtest/op_6/wallet.db
  start_height: 0
