- key: op_1.pem
  broker_id: 1
  address: /ip4/<OPERATOR_1_IP>/tcp/61180

- key: op_2.pem
  broker_id: 2
  address: /ip4/<OPERATOR_2_IP>/tcp/61180

- key: op_3.pem
  broker_id: 3
  address: /ip4/<OPERATOR_3_IP>/tcp/61180

- key: op_4.pem
  broker_id: 4
  address: /ip4/<OPERATOR_4_IP>/tcp/61180
