# =============================================================================
# CI ENVIRONMENT - Overrides to base.yaml
# =============================================================================

# =============================================================================
# COMMON CONFIGURATION
# =============================================================================

# =============================================================================
# COORDINATOR SERVICE
# =============================================================================

# =============================================================================
# BLOCK INDEXER SERVICE
# =============================================================================

# =============================================================================
# LOG INDEXER SERVICE
# =============================================================================

# =============================================================================
# TRANSACTION DISPATCHER SERVICE
# =============================================================================

key_store:
  path: "test_keystore/keyfile"
