# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.53:4445" # if running in AWS and accessed from AWS
# url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if running in AWS and accessed from outside
bitcoin_network = "testnet"

[[contracts]]
name = "FakePegManager"
address = "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"

[[contracts]]
name = "PegManager"
address = "0xBc645C71BF7053623b4fd6B3311acd5D87f1E128"

[[contracts]]
name = "SignatureManager"
address = "0x4386466074a1C9752D4618EB91ea231e43a7c0dE"

[[contracts]]
name = "CommitteeRegistry"
address = "0x2F29b6A19E1A8c460Fb2e23b0AB5359099204330"

[[contracts]]
name = "MemberRegistry"
address = "0x2B64c0E0641F563dC367fc99Fe103c00FE06C5a0"

[[contracts]]
name = "StreamManager"
address = "0x8CD8A097854B398e9eAE5Ac983E491E04E7e276E"

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
