# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://i-08db6fb8eca2d8add.us-east-2.compute.internal:4445"
bitcoin_network = "testnet"

[[contracts]]
name = "FakePegManager"
address = "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"

[[contracts]]
name = "PegManager"
address = "0x03Bc67b36F510dAbe47093979ec3cBE0D33e34c2"

[[contracts]]
name = "SignatureManager"
address = "0x37178C940BE4376cBEadcFAFA2d6aC5cf6f36046"

[[contracts]]
name = "CommitteeRegistry"
address = "0xa572343DdB10fFA608ab05b673c1aF16CfaB5b73"

[[contracts]]
name = "MemberRegistry"
address = "0xA2Af1bD9bC037D3Ba10A201C445F122B2482c227"

[[contracts]]
name = "StreamManager"
address = "0x08dc2F0694B7067551048e59690Fe611ee46a865"

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
