# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.53:4445" # if running in AWS and accessed from AWS
# url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if running in AWS and accessed from outside

indexer.storage.path = "/app/db/"
bitcoin_network = "testnet"

[[contracts]]
name = "FakePegManager"
address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"

[[contracts]]
name = "PegManager"
address = "0xAB058E8E6963B62B1E091a452e44a4f5e3C8B879"

[[contracts]]
name = "SignatureManager"
address = "0x7128826DD95Af75ACdED0CE803DD8Fc0d9819337"

[[contracts]]
name = "CommitteeRegistry"
address = "0x26f97e32B548715d7D7073BD1A34C65F12ca13CC"

[[contracts]]
name = "MemberRegistry"
address = "0xc5D96270cE96DF6865d518a9beF3298323881DBC"

[[contracts]]
name = "StreamManager"
address = "0xc4bD69eBDb7AAf864D66ecc33C60Cb9a4F7D2a91"

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/"           # This should match the volume mount in docker-compose
block_broker.host = "block-indexer"
log_broker.host = "log-indexer"
user_broker.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json"     # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json"
