# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.26.7.106:4445"
bitcoin_network = "testnet"

[[contracts]]
name = "FakePegManager"
address = "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"

[[contracts]]
name = "PegManager"
address = "0xa25B3aB9DBdBEEaB4a4d5F8dBC4a2ffA87a97aBc"

[[contracts]]
name = "SignatureManager"
address = "0x537B141C9Fd69a27B064635f694B7D3D50168a41"

[[contracts]]
name = "CommitteeRegistry"
address = "0xc1B888265Ebfcd1162797B3BF804FD08D2ccb3Dc"

[[contracts]]
name = "MemberRegistry"
address = "0x4752b4a6Cce3368cB4b6eDB8DD1137aa08594c2D"

[[contracts]]
name = "StreamManager"
address = "0x38C5d2e8a3fB87B851ab7b501a317E48fc5bFa7F"
<<<<<<< HEAD

[[contracts]]
name = "NativeBridge"
address = "0x0000000000000000000000000000000001000006"
=======
>>>>>>> 11780e5e (chore: update test contract address)

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
