# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://host.docker.internal:8545"
# url: "ws://node-container:8545" # if running anvil/node in a container
# url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if connecting to an external node
[indexer]

# Override base: start from current tip; initial_block_hash from base is ignored in this env.
start_from = "best"
storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]

storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]

key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
