# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://host.docker.internal:8545"
# url: "ws://node-container:8545" # if running anvil/node in a container
# url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if connecting to an external node
[indexer]

storage.path = "/app/db/"

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]

storage_path = "/app/db/"           # This should match the volume mount in docker-compose
block_broker.host = "block-indexer"
log_broker.host = "log-indexer"
user_broker.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]

key_store.user_path = "/keystore/user-key.json"
key_store.member_path = "/keystore/member-key.json"
