# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.53:4445" # if running in AWS and accessed from AWS
# url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if running in AWS and accessed from outside
bitcoin_network = "testnet"

[[contracts]]
name = "FakePegManager"
address = "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"

[[contracts]]
name = "PegManager"
address = "0xE4D1835c12bDb88186929BC9e8DFd831914847C4"

[[contracts]]
name = "SignatureManager"
address = "0x9eA8B0f84c5079d13159be3454e1A191459985BF"

[[contracts]]
name = "CommitteeRegistry"
address = "0x01bef9d2e307ccE31F1a976E16478f9f0F824A7d"

[[contracts]]
name = "MemberRegistry"
address = "0xfE9Bbef10a49426Ca9B1B8d78D7d57B9b4dA4Ca8"

[[contracts]]
name = "StreamManager"
address = "0x71260e163CE80566e82B26934Ea98A1C194340d3"

[[contracts]]
name = "NativeBridge"
address = "0x0000000000000000000000000000000001000006"

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
