# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.66:4445" # if running in AWS and accessed from AWS
# url: "ws://node-use2-1.regtest.rskcomputing.net.net:4445/websocket" # if running in AWS and accessed from outside
bitcoin_network = "regtest"

[[contracts]]
name = "FakePegManager"
address = "0x7Cd31D33302B6f5Bc45763487195Ae329a915beB"

[[contracts]]
name = "PeginManager"
address = "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE"

[[contracts]]
name = "PegoutManager"
address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"

[[contracts]]
name = "SignatureManager"
address = "0x7B070f39f6bd74De7Fc0678ebd1dee3b4F06853B"

[[contracts]]
name = "CommitteeRegistry"
address = "0x09cBe2b2a151A58AAae1E89C2809c2d8E1666f43"

[[contracts]]
name = "MemberRegistry"
address = "0x185DA4bbEc7DA24ec252505094E9ba13B1a5f0e6"

[[contracts]]
name = "StreamManager"
address = "0xC689FB08B10BE1080c87dC6f8EdcA7Cd20471218"

[[contracts]]
name = "ChallengeManager"
address = "0x59b670e9fA9D0A427751Af201D676719a970857b"

[[contracts]]
name = "NativeBridge"
address = "0x0000000000000000000000000000000001000006"

[indexer]

# Override base: start from current tip; initial_block_hash from base is ignored in this env.
start_from = "best"
storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/"     # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"
broker.key_path = "/app/broker.pem"

[coordinator.advance_funds]
max_zkp_status_retries = 0

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json"     # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh

[block_indexer]
broker_key_path = "/app/broker.pem"

[log_indexer]
broker_key_path = "/app/broker.pem"

[user_api]
broker_key_path = "/app/broker.pem"

# TODO(iago) rename to docker-regtest.toml and update any affected file or script