# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.66:4445" # if running in AWS and accessed from AWS
# url: "ws://node-use2-1.regtest.rskcomputing.net.net:4445/websocket" # if running in AWS and accessed from outside
bitcoin_network = "regtest"

[[contracts]]
name = "FakePegManager"
address = "0x0e19674ebc2c2B6Df3e7a1417c49b50235c61924"

[[contracts]]
name = "PegManager"
address = "0x55a7dD56B9945349511075AC9387d3bbfdd1CD69"

[[contracts]]
name = "SignatureManager"
address = "0x5C12EC3Efcbad656C161011FFf85208Ff1f5b77a"

[[contracts]]
name = "CommitteeRegistry"
address = "0x32C26AeF4b529Edb9af6bF60B089F3CEdf6C6fb8"

[[contracts]]
name = "MemberRegistry"
address = "0x5b3Fc365fd69Def5c8FcA6D7410A702497f466cF"

[[contracts]]
name = "StreamManager"
address = "0x3a380E0900864c102AcE2263A2b1BDd7D07ea4B2"

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/" # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json" # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
