# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

provider.rootstock.url = "ws://10.1.0.66:4445" # if running in AWS and accessed from AWS
# url: "ws://node-use2-1.regtest.rskcomputing.net.net:4445/websocket" # if running in AWS and accessed from outside
bitcoin_network = "regtest"

[[contracts]]
name = "FakePegManager"
address = "0x34ef74276Ea9F51d2bd591cfc1662990feA6AA5a"

[[contracts]]
name = "PegManager"
address = "0x1a85ececEFe3CD330d7c33DaCA5831323bAEE31F"

[[contracts]]
name = "SignatureManager"
address = "0xDf9dbA7085202aA4f1DE2C2D64280Bc2E9C61502"

[[contracts]]
name = "CommitteeRegistry"
address = "0x3a1dc365d41bfe86B484ac77D97a48aC856514A2"

[[contracts]]
name = "MemberRegistry"
address = "0x701AE0a93c57346DdA388B52ED6bd17fAe9A237f"

[[contracts]]
name = "StreamManager"
address = "0xaAe0db181b9B3db3E52AC1AfBd6Db45b27491fD7"

[[contracts]]
name = "PowpegBridge"
address = "0x0000000000000000000000000000000001000006"

[indexer]

storage.path = "/app/db/" # This should match the volume mount in docker-compose

# ═══════════════════════════════════════════════════════
# Coordinator
# ═══════════════════════════════════════════════════════

[coordinator]
storage_path = "/app/db/"     # This should match the volume mount in docker-compose
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"

# ═══════════════════════════════════════════════════════
# Transaction Dispatcher
# ═══════════════════════════════════════════════════════

[transaction_dispatcher]
key_store.user_path = "/keystore/user-key.json"     # should match the one configured in key-setup.sh
key_store.member_path = "/keystore/member-key.json" # should match the one configured in key-setup.sh
