[package]
name = "log-indexer"
version.workspace = true
edition = "2024"

[features]
default = ["fresh_node"] # temporary, for dev convenience
anvil = ["common/anvil"]
fresh_node = []

[dependencies]

anyhow = { workspace = true }
clap = { workspace = true }
common = { path = "../common" }
log = { workspace = true }
mockall = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
primitive-types = { workspace = true }
rand = "0.9.0"
tempfile = { workspace = true }

[lints]
workspace = true
