[package]
name = "log-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
log4rs = { workspace = true }
signal-hook = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }
definitions = { path = "../definitions" }
common = { path = "../common" }
alloy-rsk-provider = { path = "../alloy-rsk-provider" }