[package]
name = "log-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
primitive-types = { workspace = true }
env_logger = { workspace = true }
rand = "0.9.0"

[features]
test-mocks = ["common/test-mocks"]
test-utils = ["common/test-utils"]