# Custom Rust builder image with Risc0, which requires amd64 architecture (specified on ./build_builder_risc0.sh)
FROM rust:1.86-slim-bookworm

# Install build dependencies
RUN apt-get update && apt-get install -y \
    clang \
    libclang-dev \
    llvm-dev \
    build-essential \
    pkg-config \
    libssl-dev \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Risc0
RUN set -e && \
    curl -L https://risczero.com/install | bash && \
    ~/.risc0/bin/rzup install && \
    cp -r ~/.risc0 /opt/risc0

# setup SSH for private repositories
RUN mkdir -p -m 0700 ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts

LABEL org.opencontainers.image.source=https://github.com/rsksmart/union-bridge-client