# docker-compose.yml arg to specify the tag of union-contracts repository to use - if defined, contracts will be deployed for that service
ARG UNION_CONTRACTS_TAG
# docker-compose.yml arg to specify the Foundry version - if defined, Foundry will be installed for that service
ARG FOUNDRY_VERSION
# --build-arg to specify the Rust features to use (ie. anvil)
ARG FEATURES

# --- BUILDER STAGE ---

FROM union-client-builder:rust-1.86-v1 AS builder
ARG JUST_CRATE=""
ARG FEATURES=""

# setup SSH for private repositories
RUN mkdir -p -m 0700 ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts

WORKDIR /app

# copy only dependency files for better caching
COPY Cargo.toml Cargo.lock ./

# TODO create crates folder and move crates there, so we can copy it instead of the individual crates
# copy workspace members:
COPY common common
COPY block-indexer block-indexer
COPY log-indexer log-indexer
COPY transaction-dispatcher transaction-dispatcher
COPY key-manager key-manager
COPY check-fork check-fork
COPY coordinator coordinator
COPY user-api user-api
COPY actors-mocking actors-mocking

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# SSH mount for private repos
RUN --mount=type=ssh,id=default mkdir -p .cargo .&& \
    echo '[net]\ngit-fetch-with-cli = true' > .cargo/config.toml && \
    cargo fetch --locked

ENV RUST_LOG=error
ENV CARGO_TERM_QUIET=true

RUN --mount=type=ssh,id=default cargo build  --quiet --release -p actors-mocking${FEATURES:+ --features $FEATURES};

# --- RUNTIME STAGE ---

FROM debian:bookworm-slim AS runtime

# install runtime dependencies
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# copy the crate built binary
COPY --from=builder /app/target/release/actors-mocking /app/actors-mocking

# if contracts required (checked within the script): clone, build and deploy them
ARG UNION_CONTRACTS_TAG
ARG FOUNDRY_VERSION
COPY docker/dockerfile_sh/actors-mocking-setup.sh /app/actors-mocking-setup.sh
RUN --mount=type=ssh,id=default chmod +x /app/actors-mocking-setup.sh && /app/actors-mocking-setup.sh
# required by contracts-setup and also by actors-mocking that spins up anvil
ENV PATH="/opt/foundry/bin:$PATH"

# set environment variables
ENV RUST_BACKTRACE=1
ENV RUST_LOG=debug

# ENTRYPOINT is handled in docker-compose.yml