#####################################################################################################################################
# DISCLAIMER: This docker-compose file is intended for development and testing purposes only, not for production use. ###############
#####################################################################################################################################

services:
  block-indexer:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-block-indexer:${REPO_VERSION:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - CRATE=block-indexer
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ${CONFIG_PATH:-../config/docker}:/app/config:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - db-blocks:/app/db/blocks
    environment:
      - UB__provider__rootstock__url=${ROOTSTOCK_URL:-ws://host.docker.internal:8545}
    restart: no
    ports:
      - "12345"  # broker server port from the configuration
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: [ "CMD", "pgrep", "-f", "block-indexer" ] # TODO improve with health endpoint
    entrypoint: [ "/app/block-indexer", "--config-path", "/app/config" ]

  log-indexer:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-log-indexer:${REPO_VERSION:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - CRATE=log-indexer
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ${CONFIG_PATH:-../config/docker}:/app/config:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - db-logs:/app/db/logs
    environment:
      - UB__provider__rootstock__url=${ROOTSTOCK_URL:-ws://host.docker.internal:8545}
    restart: no
    ports:
      - "56789"  # broker server port from the configuration
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: [ "CMD", "pgrep", "-f", "log-indexer" ] # TODO improve with health endpoint
    entrypoint: [ "/app/log-indexer", "--config-path", "/app/config" ]

  coordinator:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-coordinator:${REPO_VERSION:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - CRATE=coordinator
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ${CONFIG_PATH:-../config/docker}:/app/config:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - keystore:/keystore
    restart: no
    environment:
      - UB__bitvmx_broker__host=${BITVMX_HOST:-host.docker.internal}
      - UB__bitvmx_broker__port=${BITVMX_PORT:-61180}
      - UB__provider__rootstock__url=${ROOTSTOCK_URL:-ws://host.docker.internal:8545}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: [ "CMD", "pgrep", "-f", "coordinator" ]
    entrypoint: [ "/app/coordinator", "--config-path", "/app/config" ]
    depends_on:
      block-indexer:
        condition: service_healthy
      log-indexer:
        condition: service_healthy
      user-api:
        condition: service_healthy

  user-api:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-user-api:${REPO_VERSION:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - CRATE=user-api
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ${CONFIG_PATH:-../config/docker}:/app/config:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - keystore:/keystore
    environment:
      - UB__provider__rootstock__url=${ROOTSTOCK_URL:-ws://host.docker.internal:8545}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
    restart: no
    ports:
      - "5551"  # http server port from the configuration
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: [ "CMD", "pgrep", "-f", "user-api" ]
    entrypoint: [ "/app/user-api", "--config-path", "/app/config" ]

volumes:
  keystore:
  db-blocks:
  db-logs:
