refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l:>5}] {m}{n}"

root:
  level: debug
  appenders:
    - stdout

loggers:
  tarpc: # from bitvmx-broker
    level: warn
  alloy_provider:
    level: warn
  alloy_rpc-client:
    level: warn