block_broker:
  host: "0.0.0.0"
  port: 12345

log_broker:
  host: "0.0.0.0"
  port: 56789

user_broker:
  host: "0.0.0.0"
  port: 5550

bitvmx_broker:
  host: "0.0.0.0"
  port: 22222

broker_client_id: 333