[package]
name = "check_gaps"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
block-indexer = { path = "../../block-indexer" }
rsk-provider = { path = "../../rsk-provider" }
common = { path = "../../common" }

anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
