bitcoin:
  network: regtest
  url: http://foo:rpcpassword@host.docker.internal:18443
  username: foo
  password: rpcpassword
  wallet: test_wallet

key_manager:
  network: regtest
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: secret_password_3
  path: /tmp/regtest/op_2/keys.db

storage:
  path: /tmp/regtest/op_2/storage.db

p2p:
  address: /ip4/172.20.0.12/tcp/61181
  key: config/keys/op_2.key
  peer_id_file: peer_id
  timeout: 5

coordinator:
  throtthle_bitcoin_updates_until_sync: 0
  throtthle_bitcoin_updates: 0
#  estimate_fee: 8

broker_storage: 
  path: /tmp/regtest/op_2/broker.db

broker_port: 33333

client: 
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000

wallet:
  db_path: /tmp/regtest/op_2/wallet.db
  start_height: 0