notifier:
  port: 56789

indexer:
  initial_block_hash: "0x9dfc314e8f2b3c81a96bef025d4b57ffdecc169010ecf170116603d5b6b565af"
  sync:
    finality_depth: 100
    batch_size: 100
  storage:
    path: "/tmp/monitor-executions/default/storage"
  cache:
    size: 1000

provider:
  rootstock:
    url: "ws://127.0.0.1:8545"

contracts:
  - name: "TestContractDyn"
    address: "0x663B50C9DA9Bd586f855aF13e91EF2f0954c9761"

  - name: "TestContractCompiled"
    address: "0x9d4b2c05818A0086e641437fcb64ab6098c7BbEc"