provider:
  rootstock:
    url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket"

contracts:
  - name: "PegManager"
    address: "<ADDRESS_HERE>"

server:
  url: "<YOUR_SERVER_URL_HERE>"
key_store:
  path: "<YOUR_KEY_STORE_PATH_HERE>"
transaction:
  gas_bumps_t1: 3