[package]
name = "qa-tools-common"
version = "0.1.0"
edition = "2024"
resolver = "2"

[[bin]]
name = "archiver"
path = "src/bin/archiver.rs"

[[bin]]
name = "clear"
path = "src/bin/clear.rs"

[dependencies]
# Dependencies from the main repository
block-indexer = { path = "../../block-indexer" }
log-indexer = { path = "../../log-indexer" }
key-manager = { path = "../../key-manager" }
common = { path = "../../common" }

# Dependencies from the qa-tools workspace
anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
regex = { workspace = true }
serde_yaml = { workspace = true }
tungstenite = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
ethers-core = { workspace = true }
ethers-signers = { workspace = true }
ethers-middleware = { workspace = true }
ethers-providers = { workspace = true }
ethers-contract = { workspace = true }
cucumber = { workspace = true }
