# ═══════════════════════════════════════════════════════
# Common Configuration
# ═══════════════════════════════════════════════════════

environment = "local"

# ═══════════════════════════════════════════════════════
# Key Store
# ═══════════════════════════════════════════════════════

[key_store]
user_path = "test_keystore/user-keyfile"
member_path = "test_keystore/member-keyfile"
