block_broker:
  host: "0.0.0.0"
  port: 12345

log_broker:
  host: "0.0.0.0"
  port: 56789

user_broker:
  host: "0.0.0.0"
  port: 5550

bitvmx_broker: # can be overriden with env vars UB_bitvmx_broker__ip and UB_bitvmx_broker__port
  host: "0.0.0.0"
  port: 9094

broker_client_id: 333

storage_path: "/fake_path/.union_bridge/database/multi-client-1"
