# Local Rootstock regtest profile for Docker operator containers.

provider.rootstock.url = "ws://host.docker.internal:4445"
environment = "local-regtest"
bitcoin_network = "regtest"

[[contracts]]
name = "TestContractDyn"
address = "0x663B50C9DA9Bd586f855aF13e91EF2f0954c9761"

[[contracts]]
name = "TestContractCompiled"
address = "0x9d4b2c05818A0086e641437fcb64ab6098c7BbEc"

[[contracts]]
name = "PeginManager"
address = "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"

[[contracts]]
name = "PegoutManager"
address = "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"

[[contracts]]
name = "SignatureManager"
address = "0x9A676e781A523b5d0C0e43731313A708CB607508"

[[contracts]]
name = "CommitteeRegistry"
address = "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"

[[contracts]]
name = "MemberRegistry"
address = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"

[[contracts]]
name = "StreamManager"
address = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"

[[contracts]]
name = "ChallengeManager"
address = "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"

[[contracts]]
name = "NativeBridge"
address = "0x0000000000000000000000000000000001000006"

[indexer]
start_from = "best"
storage.path = "/app/db/"

[block_indexer]
broker_key_path = "/app/broker.pem"

[log_indexer]
broker_key_path = "/app/broker.pem"

[coordinator]
storage_path = "/app/db/"
blocks.host = "block-indexer"
logs.host = "log-indexer"
user.host = "user-api"
broker.key_path = "/app/broker.pem"

[key_store]
user_path = "/keystore/user"
member_path = "/keystore/member"

[user_api]
broker_key_path = "/app/broker.pem"

[flows.committee]
drp_program_definition = "/app/resources/union-verifier.yaml"
