indexer:
  initial_block_hash: "<YOUR_INITIAL_BLOCK_HASH_HERE>"
  sync:
    finality_depth: 100
    batch_size: 100
  storage:
    path: "<YOUR_DB_PATH_HERE>"
  cache:
    size: 1000

provider:
  rootstock:
    url: "wss://public-node.testnet.rsk.co/websocket"

log_notifier:
  broker_port: 12345

contracts:
  - name: "PegManager"
    address: "<ADDRESS_HERE>"
  - name: "SignatureManager"
    address:  "<SIGNATURE_MANAGER_ADDRESS_HERE>"
