blockchain.config.name = regtest
blockchain.config.consensusRules.rskip144 = 0
blockchain.config.consensusRules.rskip502 = 0
targetgaslimit = 6800000
forcegaslimit = true

database.dir = /var/lib/rsk/database/regtest
keyvalue.datasource = rocksdb
transaction.accountTxRateLimit.enabled = false
scoring.punishmentEnabled = false
cache.blooms.persist-snapshot = false

peer {
  connection.timeout = 10
  port = 50505
  discovery {
    enabled = false
    ip.list = []
  }
  maxActivePeers = 30
  filter {
    maxConnections = 16
  }
}

rpc {
  maxResponseSize = 0
  providers {
    web {
      cors = "*"
      max_batch_requests_size = 100
      http {
        enabled = true
        bind_address = 0.0.0.0
        hosts = ["*"]
        port = 4444
      }
      ws {
        enabled = true
        bind_address = 0.0.0.0
        port = 4445
      }
    }
  }
}
