[package]
name = "operations"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
key-manager = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rpassword = { workspace = true }
tokio = { workspace = true }
