[package]
name = "operations"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
bitcoin = { workspace = true }
clap = { workspace = true, features = ["env"] }
hex = { workspace = true }
key-manager = { workspace = true }
op-funding = { path = "../../op-funding" }
protocol-params = { path = "../../protocol-params" }
reqwest = { workspace = true }
rpassword = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
