[package]
name = "coordinator"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition = "2024"

[features]
anvil = []

[dependencies]

alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
bitcoin = { workspace = true }
chrono = { version = "0.4.42", default-features = false, features = ["clock", "serde", "std"] }
clap = { workspace = true }
common = { path = "../common" }
hex = { workspace = true }
log = { workspace = true }
musig2 = { workspace = true }
op-funding = { path = "../op-funding" }
primitive-types = { workspace = true }
protocol-params = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.20"
sha2 = { workspace = true }
storage-backend = { workspace = true }
thiserror = { workspace = true }
tiny-keccak = { workspace = true }
transaction-dispatcher = { path = "../transaction-dispatcher", features = ["types"] }
union-contracts = { workspace = true }

uuid = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[lints]
workspace = true
