[package]
name = "coordinator"
version = "0.1.0"
edition = "2024"

[dependencies]
check-fork = { path = "../check-fork" }
common = { path = "../common" }
actors-mocking = { path = "../actors-mocking" }
check-fork-zkp = { path = "../check-fork/zkp", optional = true }
transaction-dispatcher = { path = "../transaction-dispatcher", features = ["types"] }

alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
bitcoin = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
musig2 = { workspace = true }
serde_json = { workspace = true }
union-contracts = { workspace = true }
primitive-types = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }

uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
mockall = { workspace = true }

[features]
anvil = []
zkp = ["check-fork-zkp"]
