[package]
name = "coordinator"
version = "0.1.0"
edition = "2024"

[dependencies]
check-fork = { path = "../check-fork" }
common = { path = "../common" }
actors-mocking = { path = "../actors-mocking" }
check-fork-zkp = { path = "../check-fork/zkp" }
transaction-dispatcher = { path = "../transaction-dispatcher" }

alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
union-contracts = { workspace = true }
primitive-types = { workspace = true }
# TODO(jira) https://rsklabs.atlassian.net/browse/ub-176
bitvmx-client = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }

reqwest = { version = "0.12", features = ["json", "blocking"] }
uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
mockall = { workspace = true }
mockito = "0.31"

[features]
anvil = []
