bitcoin:
  network: regtest
  url: http://foo:rpcpassword@host.docker.internal:18443
  username: foo
  password: rpcpassword
  wallet: test_wallet

key_manager:
  network: regtest
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: SeCrEt_p4ssw0rd_4!
  path: /tmp/regtest/op_3/keys.db

storage:
  path: /tmp/regtest/op_3/storage.db

comms:
  address: 172.20.0.13:61182
  priv_key: config/keys/op_3.key
  storage_path: /tmp/regtest/op_3/comms.db

broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 44444
  ip: 0.0.0.0
  priv_key: config/keys/services.key
  storage: 
    path: /tmp/regtest/op_3/broker.db

components:
  l2:
    pubkey_hash: 378ad9c58b9a3c8990cac6d662d42b715c64ef5903025367521dcbe5d925657f
    id: 0
  bitvmx:
    pubkey_hash: 1d10fa43ebbf6674d74caa3e9032711ade09d98ea7d20f89459f61152bebda1e
    id: 0
  emulator:
    pubkey_hash: c356750c04776008418c31cb1fd3d9dad936e5487358eeb8961b68831f419125
    id: 0
  prover:
    pubkey_hash: 054dba5c41ee2926a7d909cc3443fa78f2f2e257cb1d008fd75e0d3534e3ba0d
    id: 0

testing:
  l2:
    priv_key: config/keys/l2.key
    id: 0
  emulator:
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    priv_key: config/keys/prover.key
    id: 0

coordinator:
  throtthle_bitcoin_updates_until_sync: 0
  throtthle_bitcoin_updates: 0

client: 
  retry: 1
  retry_delay: 1000

wallet:
  db_path: /tmp/regtest/op_3/wallet.db
  start_height: 0
