#####################################################################################################################################
# DISCLAIMER: This docker-compose file is intended for development and testing purposes only, not for production use. ###############
#####################################################################################################################################

services:
  block-indexer:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-block-indexer:${UC_TAG:-latest}
    build:
      context: ../../
      dockerfile: docker/client/Dockerfile
      args:
        - CRATE=block-indexer
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ../../config/:/app/config/:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - db-blocks:/app/db/blocks
    environment:
      - ENV_NAME=${ENV_NAME:-dummy-env-name}
    restart: no
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: ["CMD", "pgrep", "-f", "block-indexer"] # TODO improve with health endpoint
    entrypoint: ["sh", "-c", "/app/block-indexer --env $ENV_NAME"]

  log-indexer:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-log-indexer:${UC_TAG:-latest}
    build:
      context: ../../
      dockerfile: docker/client/Dockerfile
      args:
        - CRATE=log-indexer
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ../../config/:/app/config/:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - db-logs:/app/db/logs
    environment:
      - ENV_NAME=${ENV_NAME:-dummy-env-name}
    restart: no
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: ["CMD", "pgrep", "-f", "log-indexer"] # TODO improve with health endpoint
    entrypoint: ["sh", "-c", "/app/log-indexer --env $ENV_NAME"]

  coordinator:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-coordinator:${UC_TAG:-latest}
    build:
      context: ../../
      dockerfile: docker/client/Dockerfile
      args:
        - CRATE=coordinator
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ../../config/:/app/config/:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - keystore:/keystore
      - db-coordinator:/app/db/coordinator
    restart: no
    environment:
      - UB__coordinator__bitvmx__host=${BITVMX_HOST:-dummy-bitvmx-host}
      - UB__coordinator__bitvmx__port=${BITVMX_PORT:-dummy-bitvmx-port}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - BITCOIN_NETWORK=${BITCOIN_NETWORK:-dummy-bitcoin-network}
      - ENV_NAME=${ENV_NAME:-dummy-env-name}
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: ["CMD", "pgrep", "-f", "coordinator"]
    entrypoint: ["sh", "/app/key-setup.sh"]
    command: ["sh", "-c", "/app/coordinator --env $ENV_NAME"]
    depends_on:
      block-indexer:
        condition: service_healthy
      log-indexer:
        condition: service_healthy
      user-api:
        condition: service_healthy

  user-api:
    platform: ${PLATFORM}
    image: ghcr.io/rsksmart/union-client-user-api:${UC_TAG:-latest}
    build:
      context: ../../
      dockerfile: docker/client/Dockerfile
      args:
        - CRATE=user-api
      ssh:
        - default=${SSH_AUTH_SOCK}
    volumes:
      - ../../config/:/app/config/:ro
      - ${LOGGER_PATH:-./log4rs.yaml}:/app/log4rs.yaml:ro
      - keystore:/keystore
    environment:
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - ENV_NAME=${ENV_NAME:-dummy-env-name}
      - USER_BITCOIN_WIF=${USER_BITCOIN_WIF:-}
    restart: no
    ports:
      - "${USER_API_PORT:-40001}:40001"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      test: ["CMD", "pgrep", "-f", "user-api"]
    entrypoint: ["sh", "/app/key-setup.sh"]
    command: ["sh", "-c", "/app/user-api --env $ENV_NAME"]

volumes:
  keystore:
  db-blocks:
  db-logs:
  db-coordinator:
