[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
mockall = { workspace = true, optional = true }
primitive-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log4rs = { workspace = true }
config = { workspace = true }

alloy-json-abi = "0.8.21"
lru = "0.13.0"
bitcoin = "0.32.4"
signal-hook = "0.3"
tokio = { workspace = true }
serde_yaml = "0.9.33"
log = "0.4.27"

[dev-dependencies]
test-utils = { path = "../test-utils" }

[features]
testing = ["mockall"]