[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-dyn-abi = { workspace = true }
alloy-json-abi = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true, features = ["ws"] }
alloy-pubsub = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-transport = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
mockall = { workspace = true, optional = true }
primitive-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log4rs = { workspace = true }
config = { workspace = true }
log = { workspace = true }
message-broker = { package = "bitvmx-broker", git = "ssh://git@github.com/FairgateLabs/rust-bitvmx-broker.git", rev = "2afe95510b1694d0ed87a59c9b69915f65d382e7" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
serde_yaml = "0.9.33"
lru = "0.13.0"
bitcoin = "0.32.4"
signal-hook = "0.3"
sha3 = "0.10"

[features]
test-mocks = ["mockall"]
test-utils = []
