FROM --platform=linux/amd64 ghcr.io/foundry-rs/foundry:v1.7.1@sha256:8347b728d5d393dac1c018691b36f506d23b9dcd78341d40ea0fcb11c3a19cdd

USER root
ENV NODE_VERSION=22.14.0
ENV NVM_DIR=/root/.nvm
RUN apt-get update && apt-get install -y curl \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install "$NODE_VERSION" \
    && npm install -g @openzeppelin/upgrades-core@1.44.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

WORKDIR /app
COPY . .

RUN mkdir -p out && chmod -R 777 out
RUN forge install

ENTRYPOINT ["/bin/sh", "-c"]
