[package]
name = "key-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }

alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true, features = ["keystore"] }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rand = "0.8.5"

[dev-dependencies]
tempfile = { workspace = true }
