[package]
name = "key-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
# TODO(iago) move common to workspace
alloy-json-rpc = "0.12.5"
alloy-contract = "0.12.5"
alloy-primitives = { workspace = true }
alloy-signer = "0.12.5"
alloy-signer-local = { version = "0.12.5", features = ["keystore"] }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
rand = "0.8.5"