[package]
name = "key-manager"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }

alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true, features = ["keystore"] }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
secrecy = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
