[package]
name = "monitor"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
log4rs = { workspace = true }
signal-hook = { workspace = true }
dotenv = { workspace = true }
common = { path = "../common" }
alloy-rsk-provider = { path = "../alloy-rsk-provider" }
block-indexer = { path = "../block-indexer" }
log-indexer = { path = "../log-indexer" }