[package]
name = "monitor"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bitcoin = "0.32.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
hex = "0.4.3"
primitive-types = { version = "0.13.1", features = ["std", "serde"] }
# check_fork = { git = "ssh://git@github.com/rsksmart/union-bridge-check-fork.git", tag = "0.1.0" }
# zkvm_guest = { path = "../zkvm_guest" }
# zkvm_cli_serde = { package = "cli_serde", path = "../zkvm_host/cli_serde" }
# zkvm_host = {package = "host", path = "../zkvm_host/host"} # TODO remove when done with tests
log = "0.4.22"
anyhow = "1.0.94"
env_logger = "0.11.5"
storage_backend = { package = "rust-bitvmx-storage-backend", path = "../../rust-bitvmx-storage-backend" }
alloy-provider = { version = "0.8.1", features = ["ws"] }
alloy-rpc-types = "0.8.1"
alloy-pubsub = { version = "0.8.1" }
futures-util = "0.3.31"
async-trait = "0.1.83"