name: "Act Artifacts Setup"
description: "We cannot use upload/download artifacts with Act, it's sooo slow. Therefore, we create this action to include all required dependencies for building the repo."

inputs:
  fairgate_github_token:
    description: 'GitHub token for accessing FairgateLabs repositories'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache RISC Zero
      id: cache-risc0
      uses: actions/cache@v3
      with:
        path: ~/.risc0
        key: ${{ runner.os }}-risc0-v0.4.1
        restore-keys: |
          ${{ runner.os }}-risc0-

    - name: Install RISC Zero
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        ~/.risc0/bin/rzup install

    # we cannot use upload/download artifacts with act, it's sooo slow
    # therefore, we clone this repo which is a dependency for build until https://rsklabs.atlassian.net/browse/UB-176
    - name: Checkout BitVMX workspace
      uses: actions/checkout@v4
      with:
        repository: FairgateLabs/rust-bitvmx-workspace
        token: ${{ inputs.fairgate_github_token }}
        ref: f5d15597ee27f9a659498ef5fb86f4ecee094d51
        path: rust-bitvmx-workspace
        submodules: recursive
        fetch-depth: 0