indexer:
  initial_block_hash: "0x27de5a07c7e9b812c3e7ee4c7c51fa131280ed9e16f1d70b5751034943d75c47"
  storage:
    path: "/app/db/" # This should match the volume mount in docker-compose
  cache:
    size: 1000
  sync:
    finality_depth: 100
    batch_size: 100

provider:
  rootstock:
    url: "ws://host.docker.internal:8545" # if running anvil/node on host
    # url: "ws://node-container:8545" # if running anvil/node in a container
    # url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if connecting to an external node

bitcoin_network: "testnet"

contracts:
  - name: "FakePegManager"
    address: "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"

  - name: "PegManager"
    address: "0xe7369CE3e195056666167d369dcaE7Dfb8506224"

  - name: "SignatureManager"
    address: "0xa5519ad0ee760DE721709a4774247fD8253cFf2F"

  - name: "CommitteeRegistry"
    address: "0x8d6a43b73662A1ffe875F72C90d2831371fe1992"

  - name: "MemberRegistry"
    address: "0xF009e6EFe57abE75e810a0c8C8E10b60FCf0F004"

  - name: "StreamManager"
    address: "0x26f6c30944a3f1fEab347C0f003A67050cb9c8d5"