indexer:
  initial_block_hash: "0x27de5a07c7e9b812c3e7ee4c7c51fa131280ed9e16f1d70b5751034943d75c47"
  storage:
    path: "/app/db/" # This should match the volume mount in docker-compose
  cache:
    size: 1000
  sync:
    finality_depth: 100
    batch_size: 100

provider:
  rootstock:
    url: "ws://host.docker.internal:8545" # if running anvil/node on host
    # url: "ws://node-container:8545" # if running anvil/node in a container
    # url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if connecting to an external node

bitcoin_network: "testnet"

contracts:
  - name: "FakePegManager"
    address: "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"

  - name: "PegManager"
    address: "0xf8E11D0551ceC2F4CBC0b0151Ec5C97076dDbe4e"

  - name: "SignatureManager"
    address: "0x225A1708FdF868c3d8a30eb23851D174d27Ab003"

  - name: "CommitteeRegistry"
    address: "0xd0857eE00B5DC14b1D33995a3dA155235D416839"

  - name: "MemberRegistry"
    address: "0x30Af1031e33986c104438ECEA42aB33D69Fbe795"

  - name: "StreamManager"
    address: "0xf54ea8E611c58D54EbC5b9cc20e8F85841367fB5"