indexer:
  storage:
    path: "/tmp/monitor-executions/common"
  cache:
    size: 1000

notifier:
  broker_port: 56789
  
contracts:
  - name: "TestContractDyn"
    address: "0x663B50C9DA9Bd586f855aF13e91EF2f0954c9761"

  - name: "TestContractCompiled"
    address: "0x9d4b2c05818A0086e641437fcb64ab6098c7BbEc"

  - name: "PegManager"
    address: "0x0165878A594ca255338adfa4d48449f69242Eb8F"
  - name: "FakePegManager"
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"