indexer:
  storage:
    path: "/tmp/monitor-executions/common"
  cache:
    size: 1000

notifier:
  broker_port: 56789
  
contracts:
  - name: "PegManager"
    address: "0x0165878A594ca255338adfa4d48449f69242Eb8F"
  - name: "FakePegManager"
    address: "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"
  - name: "SignatureManager"
    address: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
  - name: "CommitteeRegistry"
    address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
