# this file is intended to be used together with docker-compose.yml

services:
  block-indexer:
    networks:
      union-bridge:
        ipv4_address: 172.25.3.10

  log-indexer:
    networks:
      union-bridge:
        ipv4_address: 172.25.3.11

  transaction-dispatcher:
    networks:
      union-bridge:
        ipv4_address: 172.25.3.12

  coordinator:
    networks:
      union-bridge:
        ipv4_address: 172.25.3.13

  user-api:
    networks:
      union-bridge:
        ipv4_address: 172.25.3.15

networks:
  union-bridge:
    external: true
