# this file is intended to be used together with docker-compose.yml

services:
  block-indexer:
    networks:
      union-bridge:
        ipv4_address: 172.25.1.10

  log-indexer:
    networks:
      union-bridge:
        ipv4_address: 172.25.1.11

  transaction-dispatcher:
    networks:
      union-bridge:
        ipv4_address: 172.25.1.12

  coordinator:
    networks:
      union-bridge:
        ipv4_address: 172.25.1.13

  user-api:
    networks:
      union-bridge:
        ipv4_address: 172.25.1.15

networks:
  union-bridge:
    external: true
