indexer:
  # initial block hash to start index
  initial_block_hash: "0x0"
  storage:
    # path to db
    path: "/foo/bar"
  cache:
    # block cache size
    size: 10

provider:
  rootstock:
    url: "wss://public-node.testnet.rsk.co/websocket"
