[package]
name = "log-indexer"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition = "2024"

[features]
default = []
anvil = ["common/anvil"]

[dependencies]

anyhow = { workspace = true }
clap = { workspace = true }
common = { path = "../common" }
mockall = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
primitive-types = { workspace = true }
rand = "0.10.1"
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
