[package]
name = "log-indexer"
version.workspace = true
license.workspace = true
rust-version.workspace = true
edition = "2024"

[features]
default = []
anvil = ["common-rsk/anvil"]

[dependencies]

anyhow = { workspace = true }
clap = { workspace = true }
common-broker = { path = "../common/broker" }
common-core = { path = "../common/core" }
common-rsk = { path = "../common/rsk" }
common-runtime = { path = "../common/runtime" }
metrics = { workspace = true }
mockall = { workspace = true }
serde = { workspace = true }
storage-backend = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
common-dev = { path = "../common/dev", features = ["provider-mock"] }
primitive-types = { workspace = true }
rand = "0.10.1"
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
