block_broker:
  host: "0.0.0.0"
  port: 10002

log_broker:
  host: "0.0.0.0"
  port: 11002

bitvmx_broker: # can be overriden with env vars UB_bitvmx_broker__ip and UB_bitvmx_broker__port
  host: "0.0.0.0"
  port: 33333

broker_client_id: 102

user_broker:
  host: "0.0.0.0"
  port: 30002
