services:
  bitvmx-client:
    image: ghcr.io/fairgatelabs/rust-bitvmx-workspace/bitvmx-client:0.5.1
    # container_name: bitvmx-client-container
    restart: unless-stopped
    entrypoint: [ "./run.sh" ]
    environment:
      RUST_BACKTRACE: full
      CLIENT_OP: ${CLIENT_OP}
      BITCOIND_URL: ${BITCOIND_URL}
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f bitvmx-client" ] # Check bitvmx-client process is running
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./config/${ENVIRONMENT}/client/config:/app/config
      - db-bitvmx:/tmp

volumes:
  db-bitvmx: