indexer:
  initial_block_hash: "0xabc"
  storage:
    path: "/foo/bar"
  cache:
    size: 1000

provider:
  rootstock:
    url: "wss://public-node.testnet.rsk.co/websocket"

contracts:
  - name: "RootstockTestnetMultiFeedAdapterWithoutRoundsV1"
    address: "0x663B50C9DA9Bd586f855aF13e91EF2f0954c9761"

  - name: "MoCMedianizer"
    address: "0x9d4b2c05818A0086e641437fcb64ab6098c7BbEc"
