block_broker:
  ip: "0.0.0.0"
  port: 12345

log_broker:
  ip: "0.0.0.0"
  port: 56789

bitvmx_broker: # can be overriden with env vars UB_bitvmx_broker__ip and UB_bitvmx_broker__port
  ip: "0.0.0.0"
  port: 9094

user_broker:
  ip: "0.0.0.0"
  port: 5550

broker_client_id: 100
