blocks:
  host: "0.0.0.0"
  port: 12345

logs:
  host: "0.0.0.0"
  port: 56789

bitvmx: # can be overriden with env vars UB_bitvmx__ip and UB_bitvmx__port
  host: "0.0.0.0"
  port: 9094

user:
  host: "0.0.0.0"
  port: 5550

broker:
  client_id: 100
