coordinator_broker_client_id: 101 # read from env UB__COORDINATOR_BROKER_CLIENT_ID
broker_server_port: 30001 # read from env UB__BROKER_SERVER_PORT
http_server_port: 40001 # read from env UB__HTTP_SERVER_PORT
wallet_private_key: "YOUR_WIF_PRIVATE_KEY_HERE" # Must match WALLET_PRIVATE_KEY used by bitcoin-wallet CLI
bitcoin_network: "regtest"
