bitcoin:
  network: testnet
  url: http://bitcoin:39048j03%40slk@10.1.0.23:18332
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_3
  path: /tmp/op_2/keys.db
storage:
  path: /tmp/op_2/storage.db
comms:
  address: 10.1.1.160:61180
  priv_key: config/keys/op_2.key
  storage_path: /tmp/op_2/comms.db
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4890000
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 22222
  ip: 10.1.1.160
  priv_key: config/keys/services.key
  storage:
    path: /tmp/op_2/broker.db
components:
  l2:
    pubkey_hash: <to_patch_in_host>
    id: 0
  bitvmx:
    pubkey_hash: <to_patch_in_host>
    id: 0
  emulator:
    pubkey_hash: <to_patch_in_host>
    id: 0
  prover:
    pubkey_hash: <to_patch_in_host>
    id: 0
testing:
  l2:
    priv_key: config/keys/l2.key
    id: 0
  emulator:
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    priv_key: config/keys/prover.key
    id: 0
client:
  retry: 1
  retry_delay: 1000

wallet:
  db_path: /tmp/testnet/op_2/wallet.db
  start_height: 4890000
