bitcoin:
  network: regtest
  url: http://<bitcoin-user>:<password>@<ip>:<port>
  username: <bitcoin-user>
  password: <password>
  wallet: test_wallet

key_manager:
  network: regtest

key_storage:
  password: PLACEHOLDER_KEY_STORAGE_PASSWORD
  path: /tmp/regtest/wallet/keys.db

storage:
  path: /tmp/regtest/wallet/storage.db

wallet:
  receive_key: PLACEHOLDER_WALLET_RECEIVE_KEY
  change_key: PLACEHOLDER_WALLET_CHANGE_KEY
  db_path: /tmp/regtest/wallet/wallet.db
  start_height: 0
