[workspace]

[package]
name = "ub-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.13.1"
bitcoin = { version = "0.32", features = ["std", "rand-std", "serde"] }
bitcoincore-rpc = "0.18"
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
serde_json = "1"
reqwest = { version = "0.12.10", features = ["json", "rustls-tls", "blocking"] }
storage-backend = { package = "rust-bitvmx-storage-backend", git = "ssh://git@github.com/FairgateLabs/rust-bitvmx-storage-backend.git", rev = "7f40d056f86295e3fd2a4f268f923ca3b4e70fbf" }
bollard = "0.11.0"
futures-util = "0.3"
tokio = { version = "1.40.0", features = ["sync"] }
chrono = { version = "0.4", features = ["clock"] }
rustyline = "12"

[dev-dependencies]
tempfile = "3"
