# =============================================================================
# LOCAL ENVIRONMENT - Overrides to base.yaml
# =============================================================================
# COMMON CONFIGURATION
# =============================================================================

indexer:
  storage:
    path: "/app/db/" # This should match the volume mount in docker-compose

provider:
  rootstock:
    url: "ws://host.docker.internal:8545" # if running anvil/node on host
    # url: "ws://node-container:8545" # if running anvil/node in a container
    # url: "ws://rskj-01.testnet.ub.iovlabs.net:4445/websocket" # if connecting to an external node

# =============================================================================
# BLOCK INDEXER SERVICE
# =============================================================================

# =============================================================================
# LOG INDEXER SERVICE
# =============================================================================

# =============================================================================
# COORDINATOR SERVICE
# =============================================================================

block_broker:
  host: "block-indexer"

log_broker:
  host: "log-indexer"

user_broker:
  host: "user-api"

storage_path: "/app/db/" # This should match the volume mount in docker-compose

# =============================================================================
# USER API SERVICE
# =============================================================================

# =============================================================================
# TRANSACTION DISPATCHER SERVICE
# =============================================================================

key_store:
  path: "/keystore/key.json"
