name: QA-Tests

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:

#  sync-testomat:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '22'
#
#      - name: Push transaction dispatcher feature changes to Testomat
#        working-directory: qa-tools/transaction-dispatcher
#        run: |
#          TESTOMATIO=${{ secrets.PROJECT_REPORTING_API_KEY }} \
#          TESTOMATIO_PREPEND_DIR="Transaction dispatcher" \
#          npx check-cucumber@latest "**/*.feature" --dir features --sync

  qa-tests:
    runs-on: ubuntu-latest

    env:
      DEPLOY_LOCAL_CONTRACTS_RELATIVE_PATH: "shell/script/deploy/deploy-local.sh"
      CONTRACTS_BASEDIR: "../bitvmx-union-bridge-contracts"
      TX_DISPATCHER_URL: "http://localhost:3000"
      KEY_STORE_FILE: ${{ secrets.KEY_STORE_FILE }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_STORE_ADDRESS: ${{ vars.KEY_STORE_ADDRESS }}
      TX_DISPATCHER_CONFIG_PATH: "../config/ci"

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          fairgate_github_token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}
          contracts_github_token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          cache-build: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout BitVMX contracts
        uses: actions/checkout@v4
        with:
          repository: temp-rsk/bitvmx-union-bridge-contracts
          token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          ref: v0.0.1-alpha.2_tweaks
          path: bitvmx-union-bridge-contracts

      - name: Setup BitVMX contracts
        working-directory: bitvmx-union-bridge-contracts
        run: |
          forge install
          npm install -g @openzeppelin/upgrades-core@1.44.0

      - name: Setup keystore
        working-directory: qa-tools
        run: |
          echo "${KEY_STORE_FILE}" > test_keystore/keyfile

      - name: Run transaction dispatcher integration tests
        working-directory: qa-tools
        run: |
          RUST_BACKTRACE=1 cargo run --bin qa-tools-transaction-dispatcher -- --tags @transaction-dispatcher

#      - name: Print tests summary
#        if: ${{ env.ACT }}
#        working-directory: qa-tools
#        run:
#          cat reports/tx_dispatcher.xml
#
#      - name: Upload reports to Testomat
#        if: ${{ ! env.ACT }}
#        working-directory: qa-tools
#        run: |
#          npm install @testomatio/reporter
#          TESTOMATIO=${{ secrets.PROJECT_REPORTING_API_KEY }} \
#          TESTOMATIO_TITLE="Regression - tx dispatcher | ${{ github.ref_name }} | $(date +'%Y-%m-%d %H:%M')" \
#          npx @testomatio/reporter xml reports/tx_dispatcher.xml
