name: All Tests

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/tests/build.yml
    secrets: inherit

  crates-tests:
    needs: build
    uses: ./.github/workflows/tests/crates.yml
    secrets: inherit

  qa-tests:
    needs: build
    uses: ./.github/workflows/tests/qa.yml
    secrets: inherit