name: Automated Tests

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  automated-tests:
    name: 'Automated Tests'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:

      #########################################
      #### Needed for local tests with act ####
      #########################################
      - name: Set up Node.js
        if: ${{ env.ACT }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Rust
        id: cache-rust
        if: ${{ env.ACT }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.rustup
          key: ${{ runner.os }}-rustup-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rustup-

      - name: Install Rust
        if: ${{ env.ACT && steps.cache-rust.outputs.cache-hit != 'true' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Add Rust to PATH
        if: ${{ env.ACT }}
        run: echo "~/.cargo/bin" >> $GITHUB_PATH

      # Install RocksDB deps
      - name: Install RocksDB Dependencies
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libclang-dev clang
      #########################################
      ########## End of local section #########
      #########################################

      # TODO temporary until bitvmx-client types are extracted to a separate crate
      - name: Checkout BitVMX
        if: steps.cache-bitvmx.outputs.cache-hit != 'true'
        run: |
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "https://github.com/FairgateLabs"
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "git@github.com:FairgateLabs"
          git clone --recursive --branch main git@github.com:FairgateLabs/rust-bitvmx-workspace rust-bitvmx-workspace

      - name: Cache RISC Zero
        id: cache-risc0
        uses: actions/cache@v3
        with:
          path: ~/.risc0
          key: ${{ runner.os }}-risc0-v0.4.1
          restore-keys: |
            ${{ runner.os }}-risc0-

      - name: Install RiscZero
        if: steps.cache-risc0.outputs.cache-hit != 'true'
        run: |
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install

      - name: Checkout Our Repository
        uses: actions/checkout@v4
        with:
          path: union-bridge-client

      - name: Cache Client Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-rust-cargo-${{ hashFiles('union-bridge-client/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-cargo-

      - name: Run tests
        run: |
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "ssh://git@github.com/FairgateLabs"
          RUN_MODE=ci cargo test --features test-utils --locked
        working-directory: union-bridge-client
