name: All Tests

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  build-tests:
    name: 'Build Tests'
    uses: ./.github/workflows/wf_build_tests.yml
    secrets: inherit

  crates-tests:
    name: 'Crates Tests'
    needs: build-tests
    uses: ./.github/workflows/wf_crates_tests.yml
    secrets: inherit

  qa-tests:
    name: 'QA Tests'
    needs: build-tests
    uses: ./.github/workflows/wf_qa_tests.yml
    secrets: inherit