name: "Semgrep Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 9 * * 1'

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Checkout rules repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        repository: rootstock/semgrep-rules-rust
        path: ./semgrep-rules

    - name: Setup Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep==1.84.0

    - name: Run Semgrep
      run: |
        semgrep \
          --config=p/rust \
          --config=./semgrep-rules/security/ \
          --sarif \
          --output=semgrep.sarif \
          --verbose \
          --exclude user-api \
          --exclude actors-mocking \
          --exclude bitcoin-wallet \
          --exclude cli \
          --exclude "test*" \
          .
      continue-on-error: true

    - name: Upload SARIF file to GitHub
      uses: github/codeql-action/upload-sarif@5c8a8a642e79153f5d047b10ec1cba1d1cc65699 # v3.35.1
      if: always()
      with:
        sarif_file: semgrep.sarif
        category: semgrep
