name: Style

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          contracts_github_token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          cache-build: true

      # check code formatting
      - name: Check Code Formatting
        run: |
          rustup component add rustfmt --toolchain nightly
          cargo install cargo-sort
          cargo +nightly fmt --check
          cargo +nightly fmt --manifest-path check-fork/zkp/guest/Cargo.toml --check
          cargo sort --check
          cargo sort --check check-fork/zkp/guest

      - name: Check Clippy rules
        run: |
          RISC0_SKIP_BUILD=1 cargo clippy --workspace --all-targets --all-features

      - name: Clippy CheckForkGuest
        run: |
          RISC0_SKIP_BUILD=1 cargo clippy --manifest-path check-fork/zkp/guest/Cargo.toml --all-targets --all-features
