name: Style

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          cache-build: true

      - name: Install cargo-sort
        uses: taiki-e/install-action@0631aa6515c7d545823c67cfae7ef4fc7f490154 # v2.81.8
        with:
          tool: cargo-sort

      # check code formatting
      - name: Check Code Formatting
        run: |
          rustup component add rustfmt --toolchain nightly
          bash .hooks/format-code.sh --check

      - name: Check Clippy rules
        run: bash .hooks/check-lints.sh
