name: Tests

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  test-workspace:
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
      RUSTFLAGS: -C link-arg=-fuse-ld=lld
      CARGO_PROFILE_TEST_DEBUG: 0

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          contracts_github_token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          cache-build: true

      - name: Test Prod
        run: |
          cargo test --workspace --locked

      - name: Test Features
        run: |
          cargo test --workspace --all-features --locked

  check-all-targets:
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
      RUSTFLAGS: -C link-arg=-fuse-ld=lld
      CARGO_PROFILE_DEV_DEBUG: 0

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          contracts_github_token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          cache-build: true

      - name: Check All Targets
        run: |
          cargo check --workspace --all-targets --all-features --locked
