name: Tests

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - main
  merge_group:
    types: [ checks_requested ]
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

      # cannot be moved to common_setup action because its needed to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/common_setup
        with:
          fairgate_github_token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}
          contracts_github_token: ${{ secrets.UNION_CONTRACTS_GITHUB_TOKEN }}
          cache-build: true

      - name: Test Prod
        run: |
          cargo test --workspace --all-targets --locked

      - name: Test Features
        run: |
          cargo test --workspace --all-targets --all-features --locked