name: Integration Tests
permissions:
  contents: read
on:
  push:
    paths:
      - 'transaction-dispatcher/**'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEPLOY_LOCAL_CONTRACTS_PATH: "../../bitvmx-union-bridge-contracts/shell/script/deploy/deploy-local.sh"
      TX_DISPATCHER_URL: "http://localhost:3000"
      KEY_STORE_FILE: ${{ secrets.KEY_STORE_FILE }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      TX_DISPATCHER_CONFIG_PATH: "../config/ci"
    steps:

      - name: Set up Node.js
        if: ${{ env.ACT }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Rust
        if: ${{ env.ACT }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - name: Install RocksDB Dependencies
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libclang-dev clang

      - name: Install Foundry # enables RPC caching
        uses: foundry-rs/foundry-toolchain@v1

      - name: Add Foundry to PATH
        run: echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Checkout BitVMX contracts
        uses: actions/checkout@v4
        with:
          repository: FairgateLabs/bitvmx-union-bridge-contracts
          token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}
          ref: v0.0.1-alpha.1
          path: bitvmx-union-bridge-contracts

      - name: Checkout BitVMX workspace
        if: steps.cache-bitvmx.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: FairgateLabs/rust-bitvmx-workspace
          token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}
          ref: f5d15597ee27f9a659498ef5fb86f4ecee094d51
          path: rust-bitvmx-workspace
          submodules: recursive
          fetch-depth: 0

      - name: Restore Git metadata cache
        uses: actions/cache@v3
        id: cache-repo
        with:
          path: union-bridge-client/.git
          key: ${{ runner.os }}-repo-${{ hashFiles('union-bridge-client/**') }}
          restore-keys: |
            ${{ runner.os }}-repo-

      - name: Checkout Our Repository
        uses: actions/checkout@v4
        with:
          path: union-bridge-client
          fetch-depth: 0

      - name: Setup keystore
        working-directory: union-bridge-client/qa-tools
        run:
          echo "${KEY_STORE_FILE}" > test_keystore/keyfile
        
      - name: Run integration tests
        working-directory: union-bridge-client/qa-tools
        run: |
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "ssh://git@github.com/FairgateLabs"
          JUNIT_REPORT="reports/tx_dispatcher.xml" RUST_BACKTRACE=1 cargo run --bin qa-tools-transaction-dispatcher -- --tags @transaction-dispatcher-register-pegout
          cat reports/tx_dispatcher.xml

