name: Crates Tests WF

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  workflow_call:

jobs:
  crates-tests:
    runs-on: ubuntu-latest

    steps:

      # required to be able to import .github/actions/act_setup
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: union-bridge-client

      - name: Act Setup
        if: ${{ env.ACT }}
        uses: ./union-bridge-client/.github/actions/act_setup

      # we cannot use upload/download artifacts with act, it's sooo slow
      # therefore, we disable it (see next step also)
      - name: Download build artifacts
        if: ${{ ! env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # we cannot use upload/download artifacts with act, it's sooo slow
      # therefore, we use this tweak
      - name: Artifacts Tweak
        if: ${{ env.ACT }}
        uses: ./union-bridge-client/.github/actions/act_artifacts_tweak
        with:
          fairgate_github_token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}

      - name: Test
        working-directory: union-bridge-client
        run: |
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "ssh://git@github.com/FairgateLabs"
          export CARGO_TARGET_DIR=shared-target
          RUN_MODE=ci cargo test --features test-utils # --locked TODO(Jira) re-add --locked in scope of https://rsklabs.atlassian.net/browse/UB-176
