name: Crates Tests WF

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  workflow_call:

jobs:
  crates-tests:
    runs-on: ubuntu-latest

    steps:

      # cannot be moved to common_setup action because it's necessary to find the action itself
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: union-bridge-client

      - name: Setup
        uses: ./union-bridge-client/.github/actions/common_setup
        with:
          fairgate_github_token: ${{ secrets.FAIRGATE_GITHUB_TOKEN }}

      - name: Test
        working-directory: union-bridge-client
        run: |
          git config --global url."https://${{ secrets.FAIRGATE_GITHUB_TOKEN }}@github.com/FairgateLabs".insteadOf "ssh://git@github.com/FairgateLabs"
          export CARGO_TARGET_DIR=shared-target
          RUN_MODE=ci cargo test --features test-utils # --locked TODO(Jira) re-add --locked in scope of https://rsklabs.atlassian.net/browse/UB-176
